version: '3'
services:
  screen:
    build:
      context: .
    restart: always
    env_file:
      - ./src/config/dev.env
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
